### PR TITLE
Fix error when running eslint.

### PR DESCRIPTION
**Pull request by almarto**
-If you add "use strict"; -> you'll get an error because the use of " instead of '
	-If you add 'use strict'; -> As 'global-strict' is in mode 2(error) continues failing
Solution, change 'global-strict' to mode 1(warn), you must add 'use strict' as a global for every top file but you can use single quote

### CODE REVIEW

**Comment by ericelliott** [comment]
Did you figure out that you don't need 'use strict` in ES6 modules? Strict mode is automatic in ES6.

**Comment by almarto** [comment]
Eslint throws an error if you don't use it... it's that or remove the rule
from the eslint config.

**Comment by ericelliott** [comment]
Interesting. Sounds like the eslint config needs an update, but it's not that the rule needs removing. I think it just isn't aware we're using ES6.

Did you remember to run `npm install`?

It should work with the old version of eslint that this package.json references, but if you're installing a new version of eslint, you'll need this in your config:

```js
    "parserOptions": {
        "sourceType": "module"
    },
```

**Comment by almarto** [comment]
Yes, I ran npm install and I got v. 0.21.2
I'll try that parserOptions ;)

**Comment by ericelliott** [comment]
Feel free to try to update the dependencies, and submit a PR with the correct fix. =)

**Pull request closed without merging**
